import {
  buildWebSearchTool,
  createStreamingResponse,
  extractDomainFromUrl,
  extractDomainsFromText,
  extractOutputUrlCitations,
  hasOpenAI,
} from "../openai.js";
import {
  askMemories,
  batchCreateMemories,
  batchMoveMemories,
  batchDeleteMemories,
  addMemoryComment,
  buildCitationBlock,
  buildProjectContext,
  createMemory,
  deleteMemory,
  deleteProjectMemories,
  exportMemories,
  findRelatedMemories,
  getMemoryById,
  getMemoryStats,
  getEnrichmentQueueStats,
  getMemoryRawContent,
  listMemoryVersions,
  listProjects,
  listRecentMemories,
  listWorkspaceActivity,
  listFolderCollaborators,
  listTags,
  retryMemoryEnrichment,
  setFolderCollaboratorRole,
  removeFolderCollaborator,
  restoreMemoryVersion,
  searchMemories,
  createWorkspaceFolder,
  updateWorkspaceFolder,
  deleteWorkspaceFolder,
  updateMemory,
  updateMemoryAttachment,
  updateMemoryExtractedContent,
} from "../memoryService.js";
import {
  createCitationNoteAliasMap,
  createCitationNoteNameAliasMap,
  resolveAgentToolArgs,
} from "../chatToolArgs.js";
import {
  noteRepo,
  taskRepo,
  folderRepo,
  authRepo,
  collaborationRepo,
  providerName,
  storageBridgeMode,
} from "../storage/provider.js";
import { enrichmentQueue } from "../queue.js";
import { createAgentToolHarness } from "../agentHarness.js";
import { validateNotePayload, validateBatchPayload, validateBatchCreatePayload } from "../validate.js";
import { extractSessionTokenFromHeaders } from "../authHeaders.js";
import { subscribeActivity } from "../activityBus.js";
import {
  deleteFirebaseUser,
  firebaseChangePassword,
  firebaseSendEmailVerification,
  firebaseRefreshIdToken,
  firebaseSendPasswordResetEmail,
  firebaseSignInWithEmailPassword,
  firebaseSignUpWithEmailPassword,
  isFirebaseConfigured,
  revokeFirebaseUserSessions,
  verifyFirebaseIdToken,
} from "../firebaseAuthLazy.js";
import { config } from "../config.js";
import {
  isNeonConfigured,
  mapNeonClaimsToIdentity,
  neonSendPasswordResetEmail,
  neonSignInWithEmailPassword,
  neonSignUpWithEmailPassword,
  verifyNeonAccessToken,
} from "../neonAuth.js";
import {
  parseWorkingSetIds,
  normalizeRecentChatMessages,
  isLikelyExternalInfoRequest,
  normalizeIanaTimezone,
  inferUserTimezoneFromMessages,
  inferTaskNextRunAtFromMessages,
  isExplicitTaskCreationConfirmation,
  buildAgentNoteTitle,
} from "../chat/chatHelpers.js";
import { CHAT_TOOLS, CHAT_SYSTEM_PROMPT } from "../chat/chatToolConfig.js";
import { sendJson, sendUnauthorized, resolveErrorStatus } from "../http/responseUtils.js";
import { getRequestIp, getRequestOrigin, readJsonBody } from "../http/requestUtils.js";

export const runtimeStaticDeps = {
  fetchExternalContent: (...args) => globalThis.fetch(...args),
  buildWebSearchTool,
  createStreamingResponse,
  extractDomainFromUrl,
  extractDomainsFromText,
  extractOutputUrlCitations,
  hasOpenAI,
  askMemories,
  batchCreateMemories,
  batchMoveMemories,
  batchDeleteMemories,
  addMemoryComment,
  buildCitationBlock,
  buildProjectContext,
  createMemory,
  deleteMemory,
  deleteProjectMemories,
  exportMemories,
  findRelatedMemories,
  getMemoryById,
  getMemoryStats,
  getEnrichmentQueueStats,
  getMemoryRawContent,
  listMemoryVersions,
  listProjects,
  listRecentMemories,
  listWorkspaceActivity,
  listFolderCollaborators,
  listTags,
  retryMemoryEnrichment,
  setFolderCollaboratorRole,
  removeFolderCollaborator,
  restoreMemoryVersion,
  searchMemories,
  createWorkspaceFolder,
  updateWorkspaceFolder,
  deleteWorkspaceFolder,
  updateMemory,
  updateMemoryAttachment,
  updateMemoryExtractedContent,
  createCitationNoteAliasMap,
  createCitationNoteNameAliasMap,
  resolveAgentToolArgs,
  noteRepo,
  taskRepo,
  folderRepo,
  authRepo,
  collaborationRepo,
  providerName,
  storageBridgeMode,
  enrichmentQueue,
  createAgentToolHarness,
  validateNotePayload,
  validateBatchPayload,
  validateBatchCreatePayload,
  extractSessionTokenFromHeaders,
  subscribeActivity,
  deleteFirebaseUser,
  firebaseChangePassword,
  firebaseSendEmailVerification,
  firebaseRefreshIdToken,
  firebaseSendPasswordResetEmail,
  firebaseSignInWithEmailPassword,
  firebaseSignUpWithEmailPassword,
  isFirebaseConfigured,
  revokeFirebaseUserSessions,
  verifyFirebaseIdToken,
  config,
  isNeonConfigured,
  mapNeonClaimsToIdentity,
  neonSendPasswordResetEmail,
  neonSignInWithEmailPassword,
  neonSignUpWithEmailPassword,
  verifyNeonAccessToken,
  parseWorkingSetIds,
  normalizeRecentChatMessages,
  isLikelyExternalInfoRequest,
  normalizeIanaTimezone,
  inferUserTimezoneFromMessages,
  inferTaskNextRunAtFromMessages,
  isExplicitTaskCreationConfirmation,
  buildAgentNoteTitle,
  CHAT_TOOLS,
  CHAT_SYSTEM_PROMPT,
  sendJson,
  sendUnauthorized,
  resolveErrorStatus,
  getRequestIp,
  getRequestOrigin,
  readJsonBody,
};
